site_name: IMbeta
theme:
 name: material
 custom_dir : docs/overrides 
 language: es
 favicon: assets/favicon.svg
 logo: assets/logo.svg
 palette:
  - scheme: default
    primary: custom
    accent: custom
  - scheme: slate
    primary: custom
    accent: custom
extra_css:
 - extra.css
extra:
 current_year: 2025
nav:
 - Inicio: index.md
 - Catálogo: catalogo.md
 - Explorar: explorar.md
 - Estadísticas: estadisticas.md
 - Acerca de: acerca.md
markdown_extensions:
 - admonition
 - pymdownx.details
 - pymdownx.superfences
extra_javascript:
 - js/config.js
 - https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/dist/umd/supabase.js
 - js/auth.js
