site_name: IMProvisional
theme:
 name: material
extra_css:
 - extra.css
nav:
 - Inicio: index.md
 - Cat√°logo: catalogo.md
 - Explorar: explorar.md
 - Acerca de: acerca.md
markdown_extensions:
 - admonition
 - pymdownx.details
 - pymdownx.superfences

