site_name: IMbeta
theme:
 name: material
 custom_dir : docs/overrides 
 language: es
 favicon: assets/favicon.svg
 logo: assets/logo.svg
 palette:
  - scheme: default
    primary: custom
    accent: custom
  - scheme: slate
    primary: custom
    accent: custom
extra_css:
 - stylesheets/extra.css
 - stylesheets/media.css
extra:
 current_year: 2025
nav:
 - Inicio: index.md
 - Cat√°logo: catalogo.md
 - Explorar: explorar.md
 - Acerca de: acerca.md
 - TUL: tul.md
markdown_extensions:
 - admonition
 - pymdownx.details
 - pymdownx.superfences
extra_javascript:
 - js/config.js

